DROP TABLE IF EXISTS BOOKS;

CREATE TABLE BOOKS (
  id INT PRIMARY KEY,
  TITLE VARCHAR(250) NOT NULL,
  AUTHOR VARCHAR(250) NOT NULL,
  GENRE VARCHAR(250) NOT NULL,
  NBR_PAGES VARCHAR(250) NOT NULL,
  AVAILABLE VARCHAR(250) NOT NULL
);

